AWSTemplateFormatVersion: "2010-09-09"
Description: CloudFormation Template for Creating snsTopic
Parameters:
  
Resources:
  MySnsTopic:
    Type: AWS::SNS::Topic
    Properties:
      DisplayName: snsLab
      Tags:
        - Key: Name
          Value: SnsLab